version: '3.9'
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service1
      - service2

  service1:
    build:
      context: ./service1
    ports:
      - "8081:8081"

  service2:
    build:
      context: ./service2
    ports:
      - "8082:8082"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
      MYSQL_USER: root
      MYSQL_PASSWORD: sudo0047
    ports:
      - "3306:3306"
